language: python
python:
    - 3.6
install:
    - pip install pytest pytest-cov --upgrade
    - pip install codecov --upgrade
    - pip install pylint --upgrade
    - pip install -e . 
script:
    - py.test --cov=./
    - pylint ipynb
after_success:
    - codecov
